spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
      username: root
      password: flsnrtm@1234
      minimum-idle: 2
      connection-test-query: SELECT 'TEST'
      connection-timeout: 30000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: localhost
    port: 6379
  
server:
  tomcat:
    uri-encoding: UTF-8
    
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  check-config-location: true